### ISSUE TITLE
Crash on 1.20.6

### ISSUE THREAD

**Issue by sternschnaube** [sidit77/better-mipmaps#4]
java.lang.ClassCastException: class net.minecraft.class_7172$class_7177 cannot be cast to class net.minecraft.class_7172$class_7174 (net.minecraft.class_7172$class_7177 and net.minecraft.class_7172$class_7174 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @69b794e2)
	at net.minecraft.class_315.modify$zga000$better-mipmaps$increaseMaxMipmapLevel(class_315.java:2327)
	at net.minecraft.class_315.<init>(class_315.java:522)
	at net.minecraft.class_310.<init>(class_310.java:486)
	at net.minecraft.client.main.Main.main(Main.java:223)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by sidit77** [comment]
This looks like a conflict with another mod to me. Does this fix the issue for you?
[better-mipmaps-0.2-1.20.6.jar.zip](https://github.com/sidit77/better-mipmaps/files/15362517/better-mipmaps-0.2-1.20.6.jar.zip)

**Comment by sternschnaube** [comment]
Seems to load now.
Trying to change the mimap value gives a small issue with Remove Reloading Screen. Progress bar still there after change.

![image](https://github.com/sidit77/better-mipmaps/assets/120551916/f5e0f892-1ebe-4099-bb03-d810cb81806f)

Changed the value with vanilla textures.

![image](https://github.com/sidit77/better-mipmaps/assets/120551916/a6270c44-9e3d-455d-ab44-76f538cae354)

**Comment by sidit77** [comment]
The higher you set the mipmap setting the more likely you are to encounter issues. I would only go as high as needed (see the table in the readme).

**Comment by sternschnaube** [comment]
Then I think everything works as intended. Thanks 😊
