### ISSUE TITLE
Crash on 1.20.1

### ISSUE THREAD

**Issue by Typicalraph** [sidit77/better-mipmaps#6]
I pretty sure i have the same issue from another post called "Crash on 1.20.6" here is my crash report:

java.lang.ClassCastException: class net.minecraft.class_7172$class_7177 cannot be cast to class net.minecraft.class_7172$class_7174 (net.minecraft.class_7172$class_7177 and net.minecraft.class_7172$class_7174 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @57d5872c)
	at net.minecraft.class_315.modify$zpb000$better-mipmaps$increaseMaxMipmapLevel(class_315.java:3299)
	at net.minecraft.class_315.<init>(class_315.java:482)
	at net.minecraft.class_310.<init>(class_310.java:460)
	at net.minecraft.client.main.Main.main(Main.java:211)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by sidit77** [comment]
I added a 1.20.1 version of the fix I made for the previous issue (0.2-1.20.1).

**Comment by Typicalraph** [comment]
Fixed it Thanks
